name: Deploy Backend

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SSH to VPS and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}     # IP publique du VPS
          username: ${{ secrets.VPS_USER }} # ubuntu
          port: ${{ secrets.VPS_PORT }}     # 4423 si tu as changé le port
          key: ${{ secrets.SSH_PRIVATE_KEY }}   # <-- clé privée directe (PAS key_path)
          script: |
            set -e
            echo "==> Pull code"
            cd /opt/apps/esn-presta-back
            if [ -d .git ]; then
              git fetch --all
              git reset --hard origin/main
            else
              git clone git@github.com:Gojobyte/esn-presta-back.git .
              git checkout main || true
            fi

            echo "==> Run deploy-back.sh"
            chmod +x deploy-back.sh
            ./deploy-back.sh

            echo "==> Check health"
            curl -sfm 5 http://127.0.0.1:3001/api/health || (echo "Healthcheck failed" && exit 1)
