name: Test SSH to VPS

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: SSH to VPS and run a simple command
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            echo "✅ Connected to $(hostname)"
            whoami
            uname -a
